version: "3"

services:

  api_service:
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./api/src/:/src/
    env_file:
      - ./api/.env

  ui_service:
    build:
      context: ui/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./ui/src/:/src/
    env_file:
      - ./ui/.env
    depends_on:
      - api_service
